apiVersion: v1
kind: Secret
metadata:
  name: techdocs-overlay
  namespace: tap-install
stringData:
  techdocs-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")

    #@overlay/match by=overlay.subset({"kind": "Deployment", "metadata":{"name":"server","namespace":"tap-gui"}})
    ---
    spec:
      template:
        spec:
          containers:
          #@overlay/match by=overlay.subset({"name":"backstage"})
          - name: backstage
            #@overlay/match missing_ok=True
            env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375
            volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /output
              name: output
          #@overlay/append
          - command:
            - dockerd
            - --host
            - tcp://127.0.0.1:2375
            image: PRIVATE_IMAGE_REGISTRY/docker:dind-rootless
            imagePullPolicy: IfNotPresent
            name: dind-daemon
            resources: {}
            securityContext:
              privileged: true
              runAsUser: 0
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /etc/custom-ca-certs-data
              name: ca-certs-data
              readOnly: true
            - mountPath: /tmp
              name: tmp
            - mountPath: /output
              name: output
          #@overlay/match missing_ok=True
          volumes:
          #!- name: ca-certs-data
          #!  secret:
          #!    secretName: custom-ca-cert-data-ver-1
          #@overlay/match missing_ok=True
          - emptyDir: {}
            name: tmp
          - emptyDir: {}
            name: output