profile: full

ceip_policy_disclosed: true

shared:
  ingress_domain: FILL_ME_IN                      # @TODO: change
  ingress_issuer: tap-ingress-selfsigned          # @TODO: change
  image_registry:
    project_path: "FILL_ME_IN/tap/supply-chain"   # @TODO: change
    username: FILL_ME_IN                          # @TODO: change
    password: FILL_ME_IN                          # @TODO: change

  # @TODO: change
  ca_cert_data: |
    -----BEGIN CERTIFICATE-----
    MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
    MSQwIgYDVQQKExtEaWd...
    -----END CERTIFICATE-----

supply_chain: basic # Can take basic, testing, testing_scanning.

ootb_delivery_basic:
  service_account: default

ootb_supply_chain_basic:
  service_account: default
  registry:
    server: harbor.vrabbi.cloud
    repository: tap/supply-chain/workloads

ootb_supply_chain_testing:
  service_account: default
  registry:
    server: harbor.vrabbi.cloud
    repository: tap/supply-chain/workloads

ootb_supply_chain_testing_scanning:
  service_account: default
  scanning:
    image:
      policy: scan-policy
    source:
      policy: scan-policy
  registry:
    server: FILL_ME_IN # @TODO: change
    repository: tap/supply-chain/workloads
  # maven:
  #     repository:
  #        url: https://MAVEN-URL
  #        secret_name: "maven-creds"
#  gitops:
#   server_address: https://github.com/
#   repository_owner: guybal
#   repository_name: tap-gitops
#   branch: dev
#   commit_strategy: pull_request
#   pull_request:
#     server_kind: github
#     commit_branch: ""
#     pull_request_title: ready for review
#     pull_request_body: generated by supply chain
#   ssh_secret: git-creds

policy:
  tuf_enabled: true

buildservice:
  exclude_dependencies: true

tap_gui:
  service_type: ClusterIP

  app_config:
    # integrations allow Backstage to read or publish data using external providers such as GitHub, GitLab, Bitbucket, LDAP, or cloud providers.
#    integrations:
#      github:
#        - host: github.com
#          token: FILL_ME_IN

      # For GitHub Apps (No SSH communication):
#      github:
#        - appId: ${GITHUB_APP_ID}
#          clientId: ${GITHUB_APP_CLIENT_ID}
#          clientSecret: ${GITHUB_APP_CLIENT_SECRET}
#          allowedInstallationOwners: ['${GITHUB_ORG_NAME}']

#      gitlab:
#        - host: gitlab.com
#          token: FILL_ME_IN  # @TODO: change
#          # If `host` ISN'T `gitlab.com` apiBaseUrl: https://<GITLAB_SERVER_FQDN>/api/v4

    techdocs:
      generator:
        dockerImage: spotify/techdocs:v1.1.2
        pullImage: false
        runIn: docker

    catalog:
      locations:
        - type: url
          target: https://gitlab.com/guybalmas/tap-gui-blank-catalog/-/blob/main/catalog-info.yaml # @TODO: change    backend:

      database:
        client: pg
        connection:
          host: postgres-tap-gui-postgresql.postgres-tap-gui.svc.cluster.local  # @TODO: change
          port: 5432
          user: postgres
          password: FILL_ME_IN                                                  # @TODO: change
          ssl: false
    auth:
      allowGuestAccess: true
#      environment: tap_gui
#      providers:
#        # GitHub authentication
#        github:
#          tap_gui:
#            clientId: ${AUTH_GITHUB_CLIENT_ID}  # @TODO: change
#            clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}  # @TODO: change
#            callbackUrl: https://tap-gui.guy-tap.terasky.demo/api/auth/github/handler/frame
#        # AzureAD authentication
#        microsoft:
#          tap_gui:
#            clientId: ${AUTH_AZURE_AD_CLIENT_ID}  # @TODO: change
#            clientSecret: ${AUTH_AZURE_AD_CLIENT_SECRET}  # @TODO: change
#            tenantId: ${AUTH_AZURE_AD_TENANT_ID}  # @TODO: change
#        gitlab:
#          tap_gui:
#            clientId: ${AUTH_GITLAB_CLIENT_ID}  # @TODO: change
#            clientSecret: ${AUTH_GITLAB_CLIENT_SECRET}  # @TODO: change
#            #callbackUrl: http://tap-gui.guy-tap.terasky.demo/api/auth/gitlab/handler/frame
#            ## uncomment if using self-hosted GitLab
#            # audience: https://gitlab.company.com
#            ## uncomment if using a custom redirect URI
#            # callbackUrl: https://tap-gui.${DOMAIN_NAME}/api/auth/gitlab/handler/frame
#      loginPage:
#        github:
#          title: GitHub Login
#          message: Sign in using your GitHub account

metadata_store:
  app_service_type: ClusterIP
  ns_for_export_app_cert: '*'

grype:
  namespace: "default"
  targetImagePullSecret: "tap-registry"

excluded_packages:
  - contour.tanzu.vmware.com
  - cert-manager.tanzu.vmware.com

package_overlays:
  - name: tap-gui
    secrets:
      - name: techdocs-overlay


namespace_provisioner:
  additional_sources:

    # Add templated tekton testing pipelines for Python, Angular and Golang applications
    - git:
        ref: origin/main
        subPath: custom-resources
        url: https://github.com/terasky-int/application-accelerator-samples.git
      path: _ytt_lib/customresources   # this user-generated path must always begin with "_ytt_lib/"

    - git:
        ref: origin/main
        subPath: overlays
        url: https://github.com/terasky-int/application-accelerator-samples.git # https://github.com/vrabbi-tap/application-accelerator-samples.git
      path: _ytt_lib/customize   # this path must always be exactly "_ytt_lib/customize"
